services:
  cli-proxy-api:
    image: ${CLI_PROXY_IMAGE:-kkkk24/cliproxyapi-pro:latest}
    pull_policy: always
    container_name: cli-proxy-api

    env_file:
      - .env

    environment:
      DEPLOY: ${DEPLOY:-}
      MANAGEMENT_PASSWORD: ${MANAGEMENT_PASSWORD}
      PGSTORE_DSN: ${PGSTORE_DSN}
      PGSTORE_SCHEMA: ${PGSTORE_SCHEMA:-public}
      PGSTORE_LOCAL_PATH: ${PGSTORE_LOCAL_PATH:-/CLIProxyAPI}

    ports:
      - "8317:8317"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./logs:/CLIProxyAPI/logs
      - ./pgstore:/CLIProxyAPI/pgstore

    restart: unless-stopped
